version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-db-network
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/coursesdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
    depends_on:
      - db
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: coursesdb
      MYSQL_ROOT_PASSWORD: root
    restart: always
    ports:
      - "3306:3306"
    networks:
      - app-db-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

networks:
  app-db-network: